ALTER TABLE `users`
  ADD COLUMN `approval_status` VARCHAR(20) NOT NULL DEFAULT 'APPROVED';

ALTER TABLE `users`
  MODIFY COLUMN `role` ENUM('TEACHER', 'STUDENT', 'ADMIN') NOT NULL DEFAULT 'STUDENT';
